name: gitter-desktop
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: Where developers come to talk
description: |
 Gitter is a chat and networking platform that helps to manage, grow
 and connect communities through messaging, content and discovery.

grade: stable
confinement: strict

parts:
  gitter-desktop:
    plugin: nil
    override-build: |
      snapcraftctl build
      ARCHITECTURE=$(dpkg --print-architecture)
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        DEB_API="https://update.gitter.im/linux64/latest"
      elif [ "${ARCHITECTURE}" = "i386" ]; then
        DEB_API="https://update.gitter.im/linux32/latest"
      else
        echo "ERROR! Gitter Desktop only produces debs for amd64 and i386. Failing the build here."
        exit 1
      fi

      DEB_URL=$(wget -q -O - "${DEB_API}" 2>/dev/null | grep http-equiv | cut -d'"' -f4 | sed 's/0;url=//')
      DEB=$(basename "${DEB_URL}")
      echo "Downloading ${DEB_URL}..."
      wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"

      echo "Unpacking ${DEB}..."
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}" 2>/dev/null
      if [ "${ARCHITECTURE}" = "amd64" ]; then
        mv ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux64 ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux
        sed -i 's/linux64/linux/g' ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux/gitter.desktop
        execstack --clear-execstack ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux/nacl_irt_x86_64.nexe
      elif [ "${ARCHITECTURE}" = "i386" ]; then
        mv ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux32 ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux
        sed -i 's/linux32/linux/g' ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux/gitter.desktop
        execstack --clear-execstack ${SNAPCRAFT_PART_INSTALL}/opt/Gitter/linux/nacl_irt_x86_32.nexe
      fi

      VERSION=$(echo "${DEB}" | cut -d'_' -f2)
      echo $VERSION > $SNAPCRAFT_STAGE/version
    after:
      - desktop-gtk3
    build-packages:
      - dpkg
      - sed
      - wget
      - execstack
    stage-packages:
      - libasound2
      - libgconf2-4
      - libgl1-mesa-glx
      - libglu1-mesa
      - libnotify4
      - libnspr4
      - libnss3
      - libpulse0
      - libxss1
      - libxtst6

apps:
  gitter-desktop:
    command: bin/desktop-launch $SNAP/opt/Gitter/linux/Gitter
    desktop: opt/Gitter/linux/gitter.desktop
    # Correct the TMPDIR path for Chromium Framework/Electron to ensure
    # libappindicator has readable resources.
    # Coerce XDG_CURRENT_DESKTOP to Unity so that App Indicators
    # are used and do not fall back to Notification Area applets
    # or disappear completely.
    environment:
      TMPDIR: $XDG_RUNTIME_DIR
      XDG_CURRENT_DESKTOP: Unity
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - gsettings
      - home
      - mount-observe
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11
